# Generated by Django 4.0.3 on 2022-03-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otzovikapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='Статус модерации'),
        ),
    ]
