# Generated by Django 4.0.3 on 2022-03-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otzovikapp', '0002_alter_review_is_moderated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='product_img', verbose_name='Фото'),
        ),
    ]
